// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package testserver

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// SampleClient is the client API for Sample service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SampleClient interface {
	Simple(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type sampleClient struct {
	cc grpc.ClientConnInterface
}

func NewSampleClient(cc grpc.ClientConnInterface) SampleClient {
	return &sampleClient{cc}
}

var sampleSimpleStreamDesc = &grpc.StreamDesc{
	StreamName: "Simple",
}

func (c *sampleClient) Simple(ctx context.Context, in *SimpleRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, "/Sample/Simple", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SampleService is the service API for Sample service.
// Fields should be assigned to their respective handler implementations only before
// RegisterSampleService is called.  Any unassigned fields will result in the
// handler for that method returning an Unimplemented error.
type SampleService struct {
	Simple func(context.Context, *SimpleRequest) (*SimpleResponse, error)
}

func (s *SampleService) simple(_ interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return s.Simple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     s,
		FullMethod: "/Sample/Simple",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return s.Simple(ctx, req.(*SimpleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterSampleService registers a service implementation with a gRPC server.
func RegisterSampleService(s grpc.ServiceRegistrar, srv *SampleService) {
	srvCopy := *srv
	if srvCopy.Simple == nil {
		srvCopy.Simple = func(context.Context, *SimpleRequest) (*SimpleResponse, error) {
			return nil, status.Errorf(codes.Unimplemented, "method Simple not implemented")
		}
	}
	sd := grpc.ServiceDesc{
		ServiceName: "Sample",
		Methods: []grpc.MethodDesc{
			{
				MethodName: "Simple",
				Handler:    srvCopy.simple,
			},
		},
		Streams:  []grpc.StreamDesc{},
		Metadata: "testserver.proto",
	}

	s.RegisterService(&sd, nil)
}
